import AlertList from "../components/Alerts/AlertList";

function Alerts() {
  return (
    <>
      <div className="mb-8">
        <h1 className="text-4xl font-bold text-slate-900">
          Alerts
        </h1>

        <p className="mt-2 text-slate-500">
          View all system alerts generated by sensors.
        </p>
      </div>

      <AlertList />
    </>
  );
}

export default Alerts;